project: bracket_lab
repo_root: "/Users/omarrodriguez/Documents/projects/gambling/bracket_lab"

pipeline:
  - stage: snapshot_before
    agent: git_snapshot_before_v1
    inputs: ["task"]

  - stage: repo_index
    agent: repo_index_v1
    inputs: ["task"]

  - stage: file_context
    agent: file_context_v1
    inputs:
      - "task"
      - "README.md"
      - "docs/PRINCIPLES.md"
      - "docs/INJURY_POLICY.md"
      - "data/injuries.yaml"
      - "scripts/refresh_data.py"
      - "scripts/build_watch_list.py"
      - "dashboard/app.py"
      - "SAFE_CHECK.txt"

  - stage: plan
    agent: planner_v1
    inputs: ["task", "git/before_snapshot.json", "git/before.diff"]

  # For scaffold work, coder should be allowed to create multiple files.
  # We'll drive this by task text + allowlisting derived from file_context once files exist.
  - stage: code_fullfiles
    agent: coder_patch_llm_v1
    inputs:
      - "task"
      - "repo_tree.txt"
      - "files/README.md.txt"
      - "files/docs/PRINCIPLES.md.txt"
      - "files/docs/INJURY_POLICY.md.txt"
      - "files/data/injuries.yaml.txt"
      - "files/scripts/refresh_data.py.txt"
      - "files/scripts/build_watch_list.py.txt"
      - "files/dashboard/app.py.txt"

  - stage: diff_builder
    agent: diff_builder_v1
    inputs: 
      - "task"
      - "files/README.md.txt"
      - "files/docs/PRINCIPLES.md.txt"
      - "files/docs/INJURY_POLICY.md.txt"
      - "files/data/injuries.yaml.txt"
      - "files/scripts/refresh_data.py.txt"
      - "files/scripts/build_watch_list.py.txt"
      - "files/dashboard/app.py.txt"
      - "proposed/README.md"
      - "proposed/docs/PRINCIPLES.md"
      - "proposed/docs/INJURY_POLICY.md"
      - "proposed/data/injuries.yaml"
      - "proposed/scripts/refresh_data.py"
      - "proposed/scripts/build_watch_list.py"
      - "proposed/dashboard/app.py"

  - stage: apply
    agent: apply_patch_v1
    inputs: 
      - "task"
      - "changes.patch"
      - "files/README.md.txt"
      - "files/docs/PRINCIPLES.md.txt"
      - "files/docs/INJURY_POLICY.md.txt"
      - "files/data/injuries.yaml.txt"
      - "files/scripts/refresh_data.py.txt"
      - "files/scripts/build_watch_list.py.txt"
      - "files/dashboard/app.py.txt"

  - stage: test
    agent: tester_v1
    inputs: ["task"]

  - stage: review
    agent: reviewer_v1
    inputs: ["task", "changes.patch", "test_report.txt"]

  - stage: snapshot_after
    agent: git_snapshot_after_v1
    inputs: ["task"]

  - stage: manifest
    agent: manifest_v1
    inputs: [
        "task",
        "git/before_snapshot.json",
        "git/after_snapshot.json",
        "changes.patch",
        "test_report.txt",
        "review.md",
        "plan.json"
       ]

logging:
  runs_dir: "runs"
  artifacts_dirname: "artifacts"